"""Tests for the AID emitter."""
from __future__ import annotations

from aidkit.emitter import emit
from aidkit.model import AidFile, Annotation, Entry, Field, Header, Workflow
from aidkit.parser import parse_string


class TestEmitHeader:
    def test_basic_header(self):
        aid = AidFile(header=Header(module="mymod", lang="go", version="1.0", purpose="Test"))
        text = emit(aid)
        assert "@module mymod\n" in text
        assert "@lang go\n" in text
        assert "@version 1.0\n" in text
        assert "@purpose Test\n" in text

    def test_manifest_header(self):
        aid = AidFile(header=Header(), is_manifest=True)
        text = emit(aid)
        assert text.startswith("@manifest\n")

    def test_deps(self):
        aid = AidFile(header=Header(module="t", deps=["fmt", "os"]))
        text = emit(aid)
        assert "@deps [fmt, os]\n" in text

    def test_depends(self):
        aid = AidFile(header=Header(module="t", depends=["pkg/a", "pkg/b"]))
        text = emit(aid)
        assert "@depends [pkg/a, pkg/b]\n" in text

    def test_comments(self):
        aid = AidFile(header=Header(module="t"), comments=["// generated by tool"])
        text = emit(aid)
        assert text.startswith("// generated by tool\n")


class TestEmitEntries:
    def test_fn_entry(self):
        entry = Entry(kind="fn", name="DoThing", fields={
            "purpose": Field(name="purpose", inline_value="Does a thing"),
            "sig": Field(name="sig", inline_value="func DoThing()"),
        })
        aid = AidFile(header=Header(module="t"), entries=[entry])
        text = emit(aid)
        assert "@fn DoThing\n" in text
        assert "@purpose Does a thing\n" in text
        assert "@sig func DoThing()\n" in text

    def test_multiline_field(self):
        entry = Entry(kind="fn", name="Foo", fields={
            "errors": Field(name="errors", lines=["ErrNotFound — item missing", "ErrTimeout — deadline exceeded"]),
        })
        aid = AidFile(header=Header(module="t"), entries=[entry])
        text = emit(aid)
        assert "@errors\n" in text
        assert "  ErrNotFound" in text
        assert "  ErrTimeout" in text

    def test_multiple_entries_separated(self):
        e1 = Entry(kind="fn", name="A", fields={"sig": Field(name="sig", inline_value="func A()")})
        e2 = Entry(kind="fn", name="B", fields={"sig": Field(name="sig", inline_value="func B()")})
        aid = AidFile(header=Header(module="t"), entries=[e1, e2])
        text = emit(aid)
        assert text.count("---") == 2


class TestEmitAnnotations:
    def test_invariants(self):
        ann = Annotation(kind="invariants", fields={
            "invariants": Field(name="invariants", lines=["Buffer never nil", "Size >= 0"]),
        })
        aid = AidFile(header=Header(module="t"), annotations=[ann])
        text = emit(aid)
        assert "@invariants\n" in text
        assert "  Buffer never nil\n" in text

    def test_decision(self):
        ann = Annotation(kind="decision", name="use-mutex", fields={
            "purpose": Field(name="purpose", inline_value="Thread safety"),
            "chosen": Field(name="chosen", inline_value="sync.Mutex"),
        })
        aid = AidFile(header=Header(module="t"), annotations=[ann])
        text = emit(aid)
        assert "@decision use-mutex\n" in text


class TestEmitWorkflows:
    def test_workflow(self):
        wf = Workflow(name="request-flow", fields={
            "purpose": Field(name="purpose", inline_value="Request handling"),
            "steps": Field(name="steps", lines=["1. Parse", "2. Validate"]),
        })
        aid = AidFile(header=Header(module="t"), workflows=[wf])
        text = emit(aid)
        assert "@workflow request-flow\n" in text
        assert "@purpose Request handling\n" in text
        assert "  1. Parse\n" in text


class TestRoundTrip:
    def test_parse_emit_parse(self):
        """Parse -> emit -> parse should produce equivalent data."""
        original = """\
@module mypackage
@lang go
@version 1.0.0
@purpose A test module

---

@fn DoSomething
@sig func DoSomething(ctx context.Context) error
@purpose Does something useful
@errors
  ErrNotFound — item not found [src: handler.go:42]

---

@type Config
@kind struct
@purpose Configuration
@fields
  Name string — config name
"""
        aid1, _ = parse_string(original)
        emitted = emit(aid1)
        aid2, _ = parse_string(emitted)

        assert aid2.header.module == aid1.header.module
        assert aid2.header.lang == aid1.header.lang
        assert len(aid2.entries) == len(aid1.entries)
        assert aid2.entries[0].name == aid1.entries[0].name
        assert aid2.entries[1].name == aid1.entries[1].name
